### ISSUE TITLE
Multiscale brain simulation with TVB+NEST 1.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#328] opened 2020-03-11 15:57 UTC
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=980433036

**Comment by herr-zett** [comment] 2020-04-02 09:28
This instance gives the impression of an use case rather than actual software

**Comment by herr-zett** [comment] 2020-04-24 12:07
Duplicate of #398

**Closed by herr-zett** 2020-04-24 12:07 UTC
Labels: Collaboratory Software, new
