### ISSUE TITLE
3D atlas viewer alpha

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#271] opened 2020-03-11 15:33 UTC
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=469903650

**Comment by jagru20** [comment] 2020-10-06 12:33
this software is marked as deprecated and thus the issue is closed.

**Closed by jagru20** 2020-10-06 12:33 UTC
Labels: Collaboratory Software, attention needed, ongoing
