### ISSUE TITLE
Model Validation Framework 2.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#351] opened 2020-03-11 16:01 UTC
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=980729630

**Comment by jagru20** [comment] 2020-07-01 12:38
@apdavison mentioned, that there will be a major release to version 2.0 soon. We will wait with integration until this release and then integrate version 2.0. @apdavison could you please comment here when version 2.0 is released?

**Comment by jagru20** [comment] 2021-02-25 11:23
Is this a duplicate of #350? The source code entry links to the same repository.

**Comment by jagru20** [comment] 2021-02-25 11:25
Oh I get it. This one is the umbrella mentioned in [here](https://github.com/bweyers/HBPVisCatalogue/issues/294#issuecomment-684806468)

**Comment by jagru20** [comment] 2022-02-21 14:04
@apdavison is this still relevant or is the framework already curated in a different form?

**Comment by apdavison** [comment] 2022-02-28 14:48
I don't think it's relevant for the KG, since it covers multiple components which should have separate entries. You can close this issue.

**Comment by jagru20** [comment] 2022-03-01 07:09
thanks! closed as suggested.

**Closed by jagru20** 2022-03-01 07:09 UTC
Labels: Sent for revision, Collaboratory Software
